//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleUp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTable
    {
        public System.Guid TaskID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskContent { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public string TaskCreator { get; set; }
        public string TaskAssignedTo { get; set; }
    }
}
